/********************************************************************************
** Form generated from reading UI file 'widget.ui'
**
** Created by: Qt User Interface Compiler version 4.8.5
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_WIDGET_H
#define UI_WIDGET_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QComboBox>
#include <QtGui/QFrame>
#include <QtGui/QGridLayout>
#include <QtGui/QHeaderView>
#include <QtGui/QLCDNumber>
#include <QtGui/QLabel>
#include <QtGui/QProgressBar>
#include <QtGui/QPushButton>
#include <QtGui/QTabWidget>
#include <QtGui/QTableView>
#include <QtGui/QTextBrowser>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Widget
{
public:
    QGridLayout *gridLayout;
    QTabWidget *tabWidget;
    QWidget *tab_xtxx;
    QTextBrowser *text_zdy;
    QLCDNumber *lcd_zdy;
    QLCDNumber *lcd_zdl;
    QTextBrowser *text_zdl;
    QLabel *label_header;
    QProgressBar *pBar_soc;
    QTextBrowser *text_soc;
    QLCDNumber *lcd_soc;
    QLCDNumber *lcd_zdyc;
    QTextBrowser *text_zdyc;
    QLCDNumber *lcd_zdwc;
    QTextBrowser *text_zdwc;
    QLCDNumber *lcd_zddy_2;
    QTextBrowser *text_zddy;
    QLCDNumber *lcd_zddy_1;
    QLabel *label_zddy_loc;
    QLabel *label_zxdy_loc;
    QLCDNumber *lcd_zxdy_1;
    QTextBrowser *text_zxdy;
    QLCDNumber *lcd_zxdy_2;
    QLabel *label_zgwd_loc;
    QLCDNumber *lcd_zgwd_1;
    QTextBrowser *text_zdwd;
    QLCDNumber *lcd_zdwd_2;
    QTextBrowser *text_zgwd;
    QLCDNumber *lcd_zgwd_2;
    QLabel *label_zdwd_loc;
    QLCDNumber *lcd_zdwd_1;
    QLabel *label_pjdy_loc;
    QLCDNumber *lcd_pjdy_1;
    QTextBrowser *text_xtzt;
    QTextBrowser *text_pjdy;
    QLCDNumber *lcd_pjdy_2;
    QTextBrowser *text_value_xtzt;
    QTextBrowser *text_c1;
    QLCDNumber *lcd_c1;
    QTextBrowser *text_c2;
    QLCDNumber *lcd_c2;
    QTextBrowser *text_c3;
    QLCDNumber *lcd_c3;
    QTextBrowser *text_c4;
    QLCDNumber *lcd_c4;
    QTextBrowser *text_c5;
    QLCDNumber *lcd_c5;
    QTextBrowser *text_c6;
    QLCDNumber *lcd_c6;
    QTextBrowser *text_c7;
    QLCDNumber *lcd_c7;
    QLCDNumber *lcd_c8;
    QTextBrowser *text_c8;
    QLCDNumber *lcd_c9;
    QTextBrowser *text_c9;
    QWidget *tab_cjbxx;
    QPushButton *pbutton_right;
    QPushButton *pbutton_left;
    QFrame *frame;
    QLabel *label_xtzy;
    QLCDNumber *lcd_p2_xtdy;
    QLabel *label_xtzy_2;
    QLCDNumber *lcd_p2_dl;
    QLabel *label_xtzy_3;
    QLCDNumber *lcd_p2_soh;
    QLabel *label_xtzy_4;
    QLCDNumber *lcd_p2_soc;
    QLCDNumber *lcd_p2_rjbbh;
    QLabel *label_xtzy_5;
    QLabel *label_xtzy_6;
    QLCDNumber *lcd_p2_xtzt;
    QLabel *label_xtzy_7;
    QLCDNumber *lcd_p2_gl;
    QLabel *label_xtzy_8;
    QLCDNumber *lcd_p2_zmsl;
    QLabel *label_xtzy_9;
    QLCDNumber *lcd_p2_cdcs;
    QLabel *label_xtzy_10;
    QLCDNumber *lcd_p2_xtgzzt;
    QLabel *label_xtzy_12;
    QLabel *label_xtzy_13;
    QLCDNumber *lcd_p2_jyzz;
    QLCDNumber *lcd_p2_dczt;
    QLCDNumber *lcd_p2_smzq;
    QLabel *label_xtzy_15;
    QLabel *label_cluster;
    QFrame *frame_2;
    QLabel *label_zgdy;
    QLCDNumber *lcd_p2_zgdy;
    QLCDNumber *lcd_p2_zddy;
    QLabel *label_zddy;
    QLCDNumber *lcd_p2_zgwd;
    QLabel *label_zgwd;
    QLCDNumber *lcd_p2_zdwd;
    QLabel *label_zdwd;
    QLCDNumber *lcd_p2_szwz;
    QLabel *label_szwz;
    QFrame *frame_3;
    QTableView *tableView;
    QWidget *tab_cxxxx;
    QLabel *label_cluster_2;
    QPushButton *pbutton_left_2;
    QPushButton *pbutton_right_2;
    QComboBox *comboBox;
    QFrame *frame_4;
    QFrame *frame_5;
    QLCDNumber *lcdNumber_7;
    QLabel *label_7;
    QLCDNumber *lcdNumber_8;
    QLabel *label_8;
    QLCDNumber *lcdNumber_9;
    QLabel *label_9;
    QLCDNumber *lcdNumber_10;
    QLabel *label_10;
    QLCDNumber *lcdNumber_11;
    QLabel *label_11;
    QLCDNumber *lcdNumber_6;
    QLabel *label_6;
    QLCDNumber *lcd_zdy_12;
    QLabel *label_xtzy_11;
    QLCDNumber *lcd_zdy_16;
    QLabel *label_xtzy_14;
    QLCDNumber *lcd_zdy_17;
    QLabel *label_xtzy_16;
    QLCDNumber *lcd_zdy_18;
    QLabel *label_xtzy_17;
    QLCDNumber *lcd_zdy_19;
    QLabel *label_xtzy_18;
    QLabel *label_xtzy_19;
    QLabel *label_xtzy_20;
    QLabel *label_xtzy_21;
    QLabel *label_xtzy_22;
    QLCDNumber *lcd_zdy_20;
    QLabel *label_xtzy_23;
    QLCDNumber *lcd_zdy_21;
    QLCDNumber *lcd_zdy_22;
    QLCDNumber *lcd_zdy_23;
    QLCDNumber *lcd_zdy_24;
    QLabel *label_xtzy_24;
    QLabel *label_xtzy_25;
    QLabel *label_xtzy_26;
    QLabel *label_xtzy_27;
    QLCDNumber *lcd_zdy_25;
    QLabel *label_xtzy_28;
    QLCDNumber *lcd_zdy_26;
    QLCDNumber *lcd_zdy_27;
    QLCDNumber *lcd_zdy_28;
    QLCDNumber *lcd_zdy_29;
    QLabel *label_xtzy_29;
    QLabel *label_xtzy_30;
    QLabel *label_xtzy_31;
    QLabel *label_xtzy_32;
    QLCDNumber *lcd_zdy_30;
    QLabel *label_xtzy_33;
    QLCDNumber *lcd_zdy_31;
    QLCDNumber *lcd_zdy_32;
    QLCDNumber *lcd_zdy_33;
    QLCDNumber *lcd_zdy_34;
    QLabel *label_xtzy_34;
    QLCDNumber *lcd_zdy_35;
    QLabel *label_xtzy_35;
    QLabel *label_xtzy_36;
    QLCDNumber *lcd_zdy_36;
    QLabel *label_xtzy_37;
    QLCDNumber *lcd_zdy_37;
    QLCDNumber *lcd_zdy_38;
    QLCDNumber *lcd_zdy_39;
    QLabel *label_xtzy_38;
    QLabel *label_xtzy_39;
    QLCDNumber *lcd_zdy_40;
    QLCDNumber *lcd_zdy_41;
    QLabel *label_xtzy_40;
    QWidget *tab_gzxx;
    QTableView *tableView_2;
    QWidget *tab_xtrz;
    QTextBrowser *text_log;

    void setupUi(QWidget *Widget)
    {
        if (Widget->objectName().isEmpty())
            Widget->setObjectName(QString::fromUtf8("Widget"));
        Widget->setWindowModality(Qt::NonModal);
        Widget->resize(669, 478);
        QSizePolicy sizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(Widget->sizePolicy().hasHeightForWidth());
        Widget->setSizePolicy(sizePolicy);
        Widget->setAutoFillBackground(false);
        gridLayout = new QGridLayout(Widget);
        gridLayout->setSpacing(6);
        gridLayout->setContentsMargins(11, 11, 11, 11);
        gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
        tabWidget = new QTabWidget(Widget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setEnabled(true);
        tabWidget->setContextMenuPolicy(Qt::DefaultContextMenu);
        tabWidget->setAutoFillBackground(true);
        tabWidget->setStyleSheet(QString::fromUtf8(""));
        tabWidget->setTabPosition(QTabWidget::South);
        tabWidget->setTabShape(QTabWidget::Rounded);
        tab_xtxx = new QWidget();
        tab_xtxx->setObjectName(QString::fromUtf8("tab_xtxx"));
        text_zdy = new QTextBrowser(tab_xtxx);
        text_zdy->setObjectName(QString::fromUtf8("text_zdy"));
        text_zdy->setGeometry(QRect(40, 30, 101, 61));
        text_zdy->setAutoFillBackground(true);
        text_zdy->setStyleSheet(QString::fromUtf8("background-color: transparent;"));
        text_zdy->setFrameShape(QFrame::Box);
        text_zdy->setFrameShadow(QFrame::Sunken);
        text_zdy->setAcceptRichText(true);
        lcd_zdy = new QLCDNumber(tab_xtxx);
        lcd_zdy->setObjectName(QString::fromUtf8("lcd_zdy"));
        lcd_zdy->setGeometry(QRect(60, 60, 64, 23));
        lcd_zdy->setAutoFillBackground(false);
        lcd_zdy->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy->setFrameShape(QFrame::NoFrame);
        lcd_zdy->setFrameShadow(QFrame::Raised);
        lcd_zdy->setSmallDecimalPoint(false);
        lcd_zdy->setMode(QLCDNumber::Dec);
        lcd_zdy->setSegmentStyle(QLCDNumber::Flat);
        lcd_zdl = new QLCDNumber(tab_xtxx);
        lcd_zdl->setObjectName(QString::fromUtf8("lcd_zdl"));
        lcd_zdl->setGeometry(QRect(60, 140, 64, 23));
        lcd_zdl->setAutoFillBackground(false);
        lcd_zdl->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdl->setFrameShape(QFrame::NoFrame);
        lcd_zdl->setFrameShadow(QFrame::Raised);
        lcd_zdl->setSmallDecimalPoint(false);
        lcd_zdl->setSegmentStyle(QLCDNumber::Flat);
        text_zdl = new QTextBrowser(tab_xtxx);
        text_zdl->setObjectName(QString::fromUtf8("text_zdl"));
        text_zdl->setGeometry(QRect(40, 110, 101, 61));
        text_zdl->setAutoFillBackground(true);
        text_zdl->setStyleSheet(QString::fromUtf8("background-color: transparent;"));
        text_zdl->setFrameShape(QFrame::Box);
        text_zdl->setFrameShadow(QFrame::Sunken);
        text_zdl->setAcceptRichText(true);
        label_header = new QLabel(tab_xtxx);
        label_header->setObjectName(QString::fromUtf8("label_header"));
        label_header->setGeometry(QRect(200, 0, 211, 31));
        pBar_soc = new QProgressBar(tab_xtxx);
        pBar_soc->setObjectName(QString::fromUtf8("pBar_soc"));
        pBar_soc->setGeometry(QRect(220, 40, 171, 51));
        pBar_soc->setValue(24);
        text_soc = new QTextBrowser(tab_xtxx);
        text_soc->setObjectName(QString::fromUtf8("text_soc"));
        text_soc->setGeometry(QRect(240, 110, 61, 31));
        text_soc->setStyleSheet(QString::fromUtf8("background-color: transparent;"));
        text_soc->setFrameShape(QFrame::NoFrame);
        lcd_soc = new QLCDNumber(tab_xtxx);
        lcd_soc->setObjectName(QString::fromUtf8("lcd_soc"));
        lcd_soc->setGeometry(QRect(310, 110, 64, 23));
        lcd_soc->setAutoFillBackground(false);
        lcd_soc->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_soc->setFrameShape(QFrame::NoFrame);
        lcd_soc->setFrameShadow(QFrame::Raised);
        lcd_soc->setSmallDecimalPoint(false);
        lcd_soc->setSegmentStyle(QLCDNumber::Flat);
        lcd_zdyc = new QLCDNumber(tab_xtxx);
        lcd_zdyc->setObjectName(QString::fromUtf8("lcd_zdyc"));
        lcd_zdyc->setGeometry(QRect(480, 60, 64, 23));
        lcd_zdyc->setAutoFillBackground(false);
        lcd_zdyc->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdyc->setFrameShape(QFrame::NoFrame);
        lcd_zdyc->setFrameShadow(QFrame::Raised);
        lcd_zdyc->setSmallDecimalPoint(false);
        lcd_zdyc->setSegmentStyle(QLCDNumber::Flat);
        text_zdyc = new QTextBrowser(tab_xtxx);
        text_zdyc->setObjectName(QString::fromUtf8("text_zdyc"));
        text_zdyc->setGeometry(QRect(460, 30, 101, 61));
        text_zdyc->setAutoFillBackground(true);
        text_zdyc->setStyleSheet(QString::fromUtf8("background-color: transparent;"));
        text_zdyc->setFrameShape(QFrame::Box);
        text_zdyc->setFrameShadow(QFrame::Sunken);
        text_zdyc->setAcceptRichText(true);
        lcd_zdwc = new QLCDNumber(tab_xtxx);
        lcd_zdwc->setObjectName(QString::fromUtf8("lcd_zdwc"));
        lcd_zdwc->setGeometry(QRect(480, 140, 64, 23));
        lcd_zdwc->setAutoFillBackground(false);
        lcd_zdwc->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdwc->setFrameShape(QFrame::NoFrame);
        lcd_zdwc->setFrameShadow(QFrame::Raised);
        lcd_zdwc->setSmallDecimalPoint(false);
        lcd_zdwc->setSegmentStyle(QLCDNumber::Flat);
        text_zdwc = new QTextBrowser(tab_xtxx);
        text_zdwc->setObjectName(QString::fromUtf8("text_zdwc"));
        text_zdwc->setGeometry(QRect(460, 110, 101, 61));
        text_zdwc->setAutoFillBackground(true);
        text_zdwc->setStyleSheet(QString::fromUtf8("background-color: transparent;"));
        text_zdwc->setFrameShape(QFrame::Box);
        text_zdwc->setFrameShadow(QFrame::Sunken);
        text_zdwc->setAcceptRichText(true);
        lcd_zddy_2 = new QLCDNumber(tab_xtxx);
        lcd_zddy_2->setObjectName(QString::fromUtf8("lcd_zddy_2"));
        lcd_zddy_2->setGeometry(QRect(143, 230, 51, 21));
        lcd_zddy_2->setAutoFillBackground(false);
        lcd_zddy_2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zddy_2->setFrameShape(QFrame::NoFrame);
        lcd_zddy_2->setFrameShadow(QFrame::Raised);
        lcd_zddy_2->setSmallDecimalPoint(false);
        lcd_zddy_2->setSegmentStyle(QLCDNumber::Flat);
        text_zddy = new QTextBrowser(tab_xtxx);
        text_zddy->setObjectName(QString::fromUtf8("text_zddy"));
        text_zddy->setGeometry(QRect(30, 200, 171, 61));
        text_zddy->setAutoFillBackground(true);
        text_zddy->setStyleSheet(QString::fromUtf8("background-color: transparent;"));
        text_zddy->setFrameShape(QFrame::Box);
        text_zddy->setFrameShadow(QFrame::Sunken);
        text_zddy->setAcceptRichText(true);
        lcd_zddy_1 = new QLCDNumber(tab_xtxx);
        lcd_zddy_1->setObjectName(QString::fromUtf8("lcd_zddy_1"));
        lcd_zddy_1->setGeometry(QRect(80, 230, 51, 21));
        lcd_zddy_1->setAutoFillBackground(false);
        lcd_zddy_1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zddy_1->setFrameShape(QFrame::NoFrame);
        lcd_zddy_1->setFrameShadow(QFrame::Raised);
        lcd_zddy_1->setSmallDecimalPoint(false);
        lcd_zddy_1->setSegmentStyle(QLCDNumber::Flat);
        label_zddy_loc = new QLabel(tab_xtxx);
        label_zddy_loc->setObjectName(QString::fromUtf8("label_zddy_loc"));
        label_zddy_loc->setGeometry(QRect(40, 230, 31, 21));
        label_zxdy_loc = new QLabel(tab_xtxx);
        label_zxdy_loc->setObjectName(QString::fromUtf8("label_zxdy_loc"));
        label_zxdy_loc->setGeometry(QRect(40, 300, 31, 21));
        lcd_zxdy_1 = new QLCDNumber(tab_xtxx);
        lcd_zxdy_1->setObjectName(QString::fromUtf8("lcd_zxdy_1"));
        lcd_zxdy_1->setGeometry(QRect(80, 300, 51, 21));
        lcd_zxdy_1->setAutoFillBackground(false);
        lcd_zxdy_1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zxdy_1->setFrameShape(QFrame::NoFrame);
        lcd_zxdy_1->setFrameShadow(QFrame::Raised);
        lcd_zxdy_1->setSmallDecimalPoint(false);
        lcd_zxdy_1->setSegmentStyle(QLCDNumber::Flat);
        text_zxdy = new QTextBrowser(tab_xtxx);
        text_zxdy->setObjectName(QString::fromUtf8("text_zxdy"));
        text_zxdy->setGeometry(QRect(30, 270, 171, 61));
        text_zxdy->setAutoFillBackground(true);
        text_zxdy->setStyleSheet(QString::fromUtf8("background-color: transparent;"));
        text_zxdy->setFrameShape(QFrame::Box);
        text_zxdy->setFrameShadow(QFrame::Sunken);
        text_zxdy->setAcceptRichText(true);
        lcd_zxdy_2 = new QLCDNumber(tab_xtxx);
        lcd_zxdy_2->setObjectName(QString::fromUtf8("lcd_zxdy_2"));
        lcd_zxdy_2->setGeometry(QRect(143, 300, 51, 21));
        lcd_zxdy_2->setAutoFillBackground(false);
        lcd_zxdy_2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zxdy_2->setFrameShape(QFrame::NoFrame);
        lcd_zxdy_2->setFrameShadow(QFrame::Raised);
        lcd_zxdy_2->setSmallDecimalPoint(false);
        lcd_zxdy_2->setSegmentStyle(QLCDNumber::Flat);
        label_zgwd_loc = new QLabel(tab_xtxx);
        label_zgwd_loc->setObjectName(QString::fromUtf8("label_zgwd_loc"));
        label_zgwd_loc->setGeometry(QRect(240, 230, 31, 21));
        lcd_zgwd_1 = new QLCDNumber(tab_xtxx);
        lcd_zgwd_1->setObjectName(QString::fromUtf8("lcd_zgwd_1"));
        lcd_zgwd_1->setGeometry(QRect(280, 230, 51, 21));
        lcd_zgwd_1->setAutoFillBackground(false);
        lcd_zgwd_1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zgwd_1->setFrameShape(QFrame::NoFrame);
        lcd_zgwd_1->setFrameShadow(QFrame::Raised);
        lcd_zgwd_1->setSmallDecimalPoint(false);
        lcd_zgwd_1->setSegmentStyle(QLCDNumber::Flat);
        text_zdwd = new QTextBrowser(tab_xtxx);
        text_zdwd->setObjectName(QString::fromUtf8("text_zdwd"));
        text_zdwd->setGeometry(QRect(230, 270, 171, 61));
        text_zdwd->setAutoFillBackground(true);
        text_zdwd->setStyleSheet(QString::fromUtf8("background-color: transparent;"));
        text_zdwd->setFrameShape(QFrame::Box);
        text_zdwd->setFrameShadow(QFrame::Sunken);
        text_zdwd->setAcceptRichText(true);
        lcd_zdwd_2 = new QLCDNumber(tab_xtxx);
        lcd_zdwd_2->setObjectName(QString::fromUtf8("lcd_zdwd_2"));
        lcd_zdwd_2->setGeometry(QRect(343, 300, 51, 21));
        lcd_zdwd_2->setAutoFillBackground(false);
        lcd_zdwd_2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdwd_2->setFrameShape(QFrame::NoFrame);
        lcd_zdwd_2->setFrameShadow(QFrame::Raised);
        lcd_zdwd_2->setSmallDecimalPoint(false);
        lcd_zdwd_2->setSegmentStyle(QLCDNumber::Flat);
        text_zgwd = new QTextBrowser(tab_xtxx);
        text_zgwd->setObjectName(QString::fromUtf8("text_zgwd"));
        text_zgwd->setGeometry(QRect(230, 200, 171, 61));
        text_zgwd->setAutoFillBackground(true);
        text_zgwd->setStyleSheet(QString::fromUtf8("background-color: transparent;"));
        text_zgwd->setFrameShape(QFrame::Box);
        text_zgwd->setFrameShadow(QFrame::Sunken);
        text_zgwd->setAcceptRichText(true);
        lcd_zgwd_2 = new QLCDNumber(tab_xtxx);
        lcd_zgwd_2->setObjectName(QString::fromUtf8("lcd_zgwd_2"));
        lcd_zgwd_2->setGeometry(QRect(343, 230, 51, 21));
        lcd_zgwd_2->setAutoFillBackground(false);
        lcd_zgwd_2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zgwd_2->setFrameShape(QFrame::NoFrame);
        lcd_zgwd_2->setFrameShadow(QFrame::Raised);
        lcd_zgwd_2->setSmallDecimalPoint(false);
        lcd_zgwd_2->setSegmentStyle(QLCDNumber::Flat);
        label_zdwd_loc = new QLabel(tab_xtxx);
        label_zdwd_loc->setObjectName(QString::fromUtf8("label_zdwd_loc"));
        label_zdwd_loc->setGeometry(QRect(240, 300, 31, 21));
        lcd_zdwd_1 = new QLCDNumber(tab_xtxx);
        lcd_zdwd_1->setObjectName(QString::fromUtf8("lcd_zdwd_1"));
        lcd_zdwd_1->setGeometry(QRect(280, 300, 51, 21));
        lcd_zdwd_1->setAutoFillBackground(false);
        lcd_zdwd_1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdwd_1->setFrameShape(QFrame::NoFrame);
        lcd_zdwd_1->setFrameShadow(QFrame::Raised);
        lcd_zdwd_1->setSmallDecimalPoint(false);
        lcd_zdwd_1->setSegmentStyle(QLCDNumber::Flat);
        label_pjdy_loc = new QLabel(tab_xtxx);
        label_pjdy_loc->setObjectName(QString::fromUtf8("label_pjdy_loc"));
        label_pjdy_loc->setGeometry(QRect(440, 230, 31, 21));
        lcd_pjdy_1 = new QLCDNumber(tab_xtxx);
        lcd_pjdy_1->setObjectName(QString::fromUtf8("lcd_pjdy_1"));
        lcd_pjdy_1->setGeometry(QRect(480, 230, 51, 21));
        lcd_pjdy_1->setAutoFillBackground(false);
        lcd_pjdy_1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_pjdy_1->setFrameShape(QFrame::NoFrame);
        lcd_pjdy_1->setFrameShadow(QFrame::Raised);
        lcd_pjdy_1->setSmallDecimalPoint(false);
        lcd_pjdy_1->setSegmentStyle(QLCDNumber::Flat);
        text_xtzt = new QTextBrowser(tab_xtxx);
        text_xtzt->setObjectName(QString::fromUtf8("text_xtzt"));
        text_xtzt->setGeometry(QRect(430, 270, 171, 61));
        text_xtzt->setAutoFillBackground(true);
        text_xtzt->setStyleSheet(QString::fromUtf8("background-color: transparent;"));
        text_xtzt->setFrameShape(QFrame::Box);
        text_xtzt->setFrameShadow(QFrame::Sunken);
        text_xtzt->setAcceptRichText(true);
        text_pjdy = new QTextBrowser(tab_xtxx);
        text_pjdy->setObjectName(QString::fromUtf8("text_pjdy"));
        text_pjdy->setGeometry(QRect(430, 200, 171, 61));
        text_pjdy->setAutoFillBackground(true);
        text_pjdy->setStyleSheet(QString::fromUtf8("background-color: transparent;"));
        text_pjdy->setFrameShape(QFrame::Box);
        text_pjdy->setFrameShadow(QFrame::Sunken);
        text_pjdy->setAcceptRichText(true);
        lcd_pjdy_2 = new QLCDNumber(tab_xtxx);
        lcd_pjdy_2->setObjectName(QString::fromUtf8("lcd_pjdy_2"));
        lcd_pjdy_2->setGeometry(QRect(543, 230, 51, 21));
        lcd_pjdy_2->setAutoFillBackground(false);
        lcd_pjdy_2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_pjdy_2->setFrameShape(QFrame::NoFrame);
        lcd_pjdy_2->setFrameShadow(QFrame::Raised);
        lcd_pjdy_2->setSmallDecimalPoint(false);
        lcd_pjdy_2->setSegmentStyle(QLCDNumber::Flat);
        text_value_xtzt = new QTextBrowser(tab_xtxx);
        text_value_xtzt->setObjectName(QString::fromUtf8("text_value_xtzt"));
        text_value_xtzt->setGeometry(QRect(460, 300, 121, 21));
        text_value_xtzt->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        text_c1 = new QTextBrowser(tab_xtxx);
        text_c1->setObjectName(QString::fromUtf8("text_c1"));
        text_c1->setGeometry(QRect(30, 360, 31, 31));
        lcd_c1 = new QLCDNumber(tab_xtxx);
        lcd_c1->setObjectName(QString::fromUtf8("lcd_c1"));
        lcd_c1->setGeometry(QRect(20, 400, 51, 21));
        lcd_c1->setAutoFillBackground(false);
        lcd_c1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_c1->setFrameShape(QFrame::NoFrame);
        lcd_c1->setFrameShadow(QFrame::Raised);
        lcd_c1->setSmallDecimalPoint(false);
        lcd_c1->setSegmentStyle(QLCDNumber::Flat);
        text_c2 = new QTextBrowser(tab_xtxx);
        text_c2->setObjectName(QString::fromUtf8("text_c2"));
        text_c2->setGeometry(QRect(100, 360, 31, 31));
        lcd_c2 = new QLCDNumber(tab_xtxx);
        lcd_c2->setObjectName(QString::fromUtf8("lcd_c2"));
        lcd_c2->setGeometry(QRect(90, 400, 51, 21));
        lcd_c2->setAutoFillBackground(false);
        lcd_c2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_c2->setFrameShape(QFrame::NoFrame);
        lcd_c2->setFrameShadow(QFrame::Raised);
        lcd_c2->setSmallDecimalPoint(false);
        lcd_c2->setSegmentStyle(QLCDNumber::Flat);
        text_c3 = new QTextBrowser(tab_xtxx);
        text_c3->setObjectName(QString::fromUtf8("text_c3"));
        text_c3->setGeometry(QRect(170, 360, 31, 31));
        lcd_c3 = new QLCDNumber(tab_xtxx);
        lcd_c3->setObjectName(QString::fromUtf8("lcd_c3"));
        lcd_c3->setGeometry(QRect(160, 400, 51, 21));
        lcd_c3->setAutoFillBackground(false);
        lcd_c3->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_c3->setFrameShape(QFrame::NoFrame);
        lcd_c3->setFrameShadow(QFrame::Raised);
        lcd_c3->setSmallDecimalPoint(false);
        lcd_c3->setSegmentStyle(QLCDNumber::Flat);
        text_c4 = new QTextBrowser(tab_xtxx);
        text_c4->setObjectName(QString::fromUtf8("text_c4"));
        text_c4->setGeometry(QRect(240, 360, 31, 31));
        lcd_c4 = new QLCDNumber(tab_xtxx);
        lcd_c4->setObjectName(QString::fromUtf8("lcd_c4"));
        lcd_c4->setGeometry(QRect(230, 400, 51, 21));
        lcd_c4->setAutoFillBackground(false);
        lcd_c4->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_c4->setFrameShape(QFrame::NoFrame);
        lcd_c4->setFrameShadow(QFrame::Raised);
        lcd_c4->setSmallDecimalPoint(false);
        lcd_c4->setSegmentStyle(QLCDNumber::Flat);
        text_c5 = new QTextBrowser(tab_xtxx);
        text_c5->setObjectName(QString::fromUtf8("text_c5"));
        text_c5->setGeometry(QRect(310, 360, 31, 31));
        lcd_c5 = new QLCDNumber(tab_xtxx);
        lcd_c5->setObjectName(QString::fromUtf8("lcd_c5"));
        lcd_c5->setGeometry(QRect(300, 400, 51, 21));
        lcd_c5->setAutoFillBackground(false);
        lcd_c5->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_c5->setFrameShape(QFrame::NoFrame);
        lcd_c5->setFrameShadow(QFrame::Raised);
        lcd_c5->setSmallDecimalPoint(false);
        lcd_c5->setSegmentStyle(QLCDNumber::Flat);
        text_c6 = new QTextBrowser(tab_xtxx);
        text_c6->setObjectName(QString::fromUtf8("text_c6"));
        text_c6->setGeometry(QRect(380, 360, 31, 31));
        lcd_c6 = new QLCDNumber(tab_xtxx);
        lcd_c6->setObjectName(QString::fromUtf8("lcd_c6"));
        lcd_c6->setGeometry(QRect(370, 400, 51, 21));
        lcd_c6->setAutoFillBackground(false);
        lcd_c6->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_c6->setFrameShape(QFrame::NoFrame);
        lcd_c6->setFrameShadow(QFrame::Raised);
        lcd_c6->setSmallDecimalPoint(false);
        lcd_c6->setSegmentStyle(QLCDNumber::Flat);
        text_c7 = new QTextBrowser(tab_xtxx);
        text_c7->setObjectName(QString::fromUtf8("text_c7"));
        text_c7->setGeometry(QRect(450, 360, 31, 31));
        lcd_c7 = new QLCDNumber(tab_xtxx);
        lcd_c7->setObjectName(QString::fromUtf8("lcd_c7"));
        lcd_c7->setGeometry(QRect(440, 400, 51, 21));
        lcd_c7->setAutoFillBackground(false);
        lcd_c7->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_c7->setFrameShape(QFrame::NoFrame);
        lcd_c7->setFrameShadow(QFrame::Raised);
        lcd_c7->setSmallDecimalPoint(false);
        lcd_c7->setSegmentStyle(QLCDNumber::Flat);
        lcd_c8 = new QLCDNumber(tab_xtxx);
        lcd_c8->setObjectName(QString::fromUtf8("lcd_c8"));
        lcd_c8->setGeometry(QRect(510, 400, 51, 21));
        lcd_c8->setAutoFillBackground(false);
        lcd_c8->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_c8->setFrameShape(QFrame::NoFrame);
        lcd_c8->setFrameShadow(QFrame::Raised);
        lcd_c8->setSmallDecimalPoint(false);
        lcd_c8->setSegmentStyle(QLCDNumber::Flat);
        text_c8 = new QTextBrowser(tab_xtxx);
        text_c8->setObjectName(QString::fromUtf8("text_c8"));
        text_c8->setGeometry(QRect(520, 360, 31, 31));
        lcd_c9 = new QLCDNumber(tab_xtxx);
        lcd_c9->setObjectName(QString::fromUtf8("lcd_c9"));
        lcd_c9->setGeometry(QRect(580, 400, 51, 21));
        lcd_c9->setAutoFillBackground(false);
        lcd_c9->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_c9->setFrameShape(QFrame::NoFrame);
        lcd_c9->setFrameShadow(QFrame::Raised);
        lcd_c9->setSmallDecimalPoint(false);
        lcd_c9->setSegmentStyle(QLCDNumber::Flat);
        text_c9 = new QTextBrowser(tab_xtxx);
        text_c9->setObjectName(QString::fromUtf8("text_c9"));
        text_c9->setGeometry(QRect(590, 360, 31, 31));
        tabWidget->addTab(tab_xtxx, QString());
        text_zdl->raise();
        text_zdyc->raise();
        text_zdwc->raise();
        text_pjdy->raise();
        text_zgwd->raise();
        text_zddy->raise();
        text_zxdy->raise();
        text_zdy->raise();
        lcd_zdy->raise();
        lcd_zdl->raise();
        label_header->raise();
        pBar_soc->raise();
        text_soc->raise();
        lcd_soc->raise();
        lcd_zdyc->raise();
        lcd_zdwc->raise();
        lcd_zddy_2->raise();
        lcd_zddy_1->raise();
        label_zddy_loc->raise();
        label_zxdy_loc->raise();
        lcd_zxdy_1->raise();
        lcd_zxdy_2->raise();
        label_zgwd_loc->raise();
        lcd_zgwd_1->raise();
        text_zdwd->raise();
        lcd_zdwd_2->raise();
        lcd_zgwd_2->raise();
        label_zdwd_loc->raise();
        lcd_zdwd_1->raise();
        label_pjdy_loc->raise();
        lcd_pjdy_1->raise();
        text_xtzt->raise();
        lcd_pjdy_2->raise();
        text_value_xtzt->raise();
        text_c1->raise();
        lcd_c1->raise();
        text_c2->raise();
        lcd_c2->raise();
        text_c3->raise();
        lcd_c3->raise();
        text_c4->raise();
        lcd_c4->raise();
        text_c5->raise();
        lcd_c5->raise();
        text_c6->raise();
        lcd_c6->raise();
        text_c7->raise();
        lcd_c7->raise();
        lcd_c8->raise();
        text_c8->raise();
        lcd_c9->raise();
        text_c9->raise();
        tab_cjbxx = new QWidget();
        tab_cjbxx->setObjectName(QString::fromUtf8("tab_cjbxx"));
        pbutton_right = new QPushButton(tab_cjbxx);
        pbutton_right->setObjectName(QString::fromUtf8("pbutton_right"));
        pbutton_right->setGeometry(QRect(140, 20, 31, 81));
        pbutton_left = new QPushButton(tab_cjbxx);
        pbutton_left->setObjectName(QString::fromUtf8("pbutton_left"));
        pbutton_left->setGeometry(QRect(20, 20, 31, 81));
        frame = new QFrame(tab_cjbxx);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(200, 20, 431, 111));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        label_xtzy = new QLabel(frame);
        label_xtzy->setObjectName(QString::fromUtf8("label_xtzy"));
        label_xtzy->setGeometry(QRect(10, 10, 62, 17));
        lcd_p2_xtdy = new QLCDNumber(frame);
        lcd_p2_xtdy->setObjectName(QString::fromUtf8("lcd_p2_xtdy"));
        lcd_p2_xtdy->setGeometry(QRect(90, 10, 51, 16));
        lcd_p2_xtdy->setAutoFillBackground(false);
        lcd_p2_xtdy->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_p2_xtdy->setFrameShape(QFrame::NoFrame);
        lcd_p2_xtdy->setFrameShadow(QFrame::Raised);
        lcd_p2_xtdy->setSmallDecimalPoint(false);
        lcd_p2_xtdy->setMode(QLCDNumber::Dec);
        lcd_p2_xtdy->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_2 = new QLabel(frame);
        label_xtzy_2->setObjectName(QString::fromUtf8("label_xtzy_2"));
        label_xtzy_2->setGeometry(QRect(10, 30, 61, 16));
        lcd_p2_dl = new QLCDNumber(frame);
        lcd_p2_dl->setObjectName(QString::fromUtf8("lcd_p2_dl"));
        lcd_p2_dl->setGeometry(QRect(90, 30, 51, 16));
        lcd_p2_dl->setAutoFillBackground(false);
        lcd_p2_dl->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_p2_dl->setFrameShape(QFrame::NoFrame);
        lcd_p2_dl->setFrameShadow(QFrame::Raised);
        lcd_p2_dl->setSmallDecimalPoint(false);
        lcd_p2_dl->setMode(QLCDNumber::Dec);
        lcd_p2_dl->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_3 = new QLabel(frame);
        label_xtzy_3->setObjectName(QString::fromUtf8("label_xtzy_3"));
        label_xtzy_3->setGeometry(QRect(10, 50, 61, 16));
        lcd_p2_soh = new QLCDNumber(frame);
        lcd_p2_soh->setObjectName(QString::fromUtf8("lcd_p2_soh"));
        lcd_p2_soh->setGeometry(QRect(90, 70, 51, 16));
        lcd_p2_soh->setAutoFillBackground(false);
        lcd_p2_soh->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_p2_soh->setFrameShape(QFrame::NoFrame);
        lcd_p2_soh->setFrameShadow(QFrame::Raised);
        lcd_p2_soh->setSmallDecimalPoint(false);
        lcd_p2_soh->setMode(QLCDNumber::Dec);
        lcd_p2_soh->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_4 = new QLabel(frame);
        label_xtzy_4->setObjectName(QString::fromUtf8("label_xtzy_4"));
        label_xtzy_4->setGeometry(QRect(10, 70, 62, 17));
        lcd_p2_soc = new QLCDNumber(frame);
        lcd_p2_soc->setObjectName(QString::fromUtf8("lcd_p2_soc"));
        lcd_p2_soc->setGeometry(QRect(90, 50, 51, 16));
        lcd_p2_soc->setAutoFillBackground(false);
        lcd_p2_soc->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_p2_soc->setFrameShape(QFrame::NoFrame);
        lcd_p2_soc->setFrameShadow(QFrame::Raised);
        lcd_p2_soc->setSmallDecimalPoint(false);
        lcd_p2_soc->setMode(QLCDNumber::Dec);
        lcd_p2_soc->setSegmentStyle(QLCDNumber::Flat);
        lcd_p2_rjbbh = new QLCDNumber(frame);
        lcd_p2_rjbbh->setObjectName(QString::fromUtf8("lcd_p2_rjbbh"));
        lcd_p2_rjbbh->setGeometry(QRect(90, 90, 51, 16));
        lcd_p2_rjbbh->setAutoFillBackground(false);
        lcd_p2_rjbbh->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_p2_rjbbh->setFrameShape(QFrame::NoFrame);
        lcd_p2_rjbbh->setFrameShadow(QFrame::Raised);
        lcd_p2_rjbbh->setSmallDecimalPoint(false);
        lcd_p2_rjbbh->setMode(QLCDNumber::Dec);
        lcd_p2_rjbbh->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_5 = new QLabel(frame);
        label_xtzy_5->setObjectName(QString::fromUtf8("label_xtzy_5"));
        label_xtzy_5->setGeometry(QRect(10, 90, 71, 17));
        label_xtzy_6 = new QLabel(frame);
        label_xtzy_6->setObjectName(QString::fromUtf8("label_xtzy_6"));
        label_xtzy_6->setGeometry(QRect(150, 10, 71, 17));
        lcd_p2_xtzt = new QLCDNumber(frame);
        lcd_p2_xtzt->setObjectName(QString::fromUtf8("lcd_p2_xtzt"));
        lcd_p2_xtzt->setGeometry(QRect(240, 10, 51, 16));
        lcd_p2_xtzt->setAutoFillBackground(false);
        lcd_p2_xtzt->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_p2_xtzt->setFrameShape(QFrame::NoFrame);
        lcd_p2_xtzt->setFrameShadow(QFrame::Raised);
        lcd_p2_xtzt->setSmallDecimalPoint(false);
        lcd_p2_xtzt->setMode(QLCDNumber::Dec);
        lcd_p2_xtzt->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_7 = new QLabel(frame);
        label_xtzy_7->setObjectName(QString::fromUtf8("label_xtzy_7"));
        label_xtzy_7->setGeometry(QRect(150, 30, 71, 17));
        lcd_p2_gl = new QLCDNumber(frame);
        lcd_p2_gl->setObjectName(QString::fromUtf8("lcd_p2_gl"));
        lcd_p2_gl->setGeometry(QRect(240, 30, 51, 16));
        lcd_p2_gl->setAutoFillBackground(false);
        lcd_p2_gl->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_p2_gl->setFrameShape(QFrame::NoFrame);
        lcd_p2_gl->setFrameShadow(QFrame::Raised);
        lcd_p2_gl->setSmallDecimalPoint(false);
        lcd_p2_gl->setMode(QLCDNumber::Dec);
        lcd_p2_gl->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_8 = new QLabel(frame);
        label_xtzy_8->setObjectName(QString::fromUtf8("label_xtzy_8"));
        label_xtzy_8->setGeometry(QRect(150, 50, 71, 17));
        lcd_p2_zmsl = new QLCDNumber(frame);
        lcd_p2_zmsl->setObjectName(QString::fromUtf8("lcd_p2_zmsl"));
        lcd_p2_zmsl->setGeometry(QRect(240, 50, 51, 16));
        lcd_p2_zmsl->setAutoFillBackground(false);
        lcd_p2_zmsl->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_p2_zmsl->setFrameShape(QFrame::NoFrame);
        lcd_p2_zmsl->setFrameShadow(QFrame::Raised);
        lcd_p2_zmsl->setSmallDecimalPoint(false);
        lcd_p2_zmsl->setMode(QLCDNumber::Dec);
        lcd_p2_zmsl->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_9 = new QLabel(frame);
        label_xtzy_9->setObjectName(QString::fromUtf8("label_xtzy_9"));
        label_xtzy_9->setGeometry(QRect(150, 70, 71, 17));
        lcd_p2_cdcs = new QLCDNumber(frame);
        lcd_p2_cdcs->setObjectName(QString::fromUtf8("lcd_p2_cdcs"));
        lcd_p2_cdcs->setGeometry(QRect(240, 70, 51, 16));
        lcd_p2_cdcs->setAutoFillBackground(false);
        lcd_p2_cdcs->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_p2_cdcs->setFrameShape(QFrame::NoFrame);
        lcd_p2_cdcs->setFrameShadow(QFrame::Raised);
        lcd_p2_cdcs->setSmallDecimalPoint(false);
        lcd_p2_cdcs->setMode(QLCDNumber::Dec);
        lcd_p2_cdcs->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_10 = new QLabel(frame);
        label_xtzy_10->setObjectName(QString::fromUtf8("label_xtzy_10"));
        label_xtzy_10->setGeometry(QRect(150, 90, 81, 17));
        lcd_p2_xtgzzt = new QLCDNumber(frame);
        lcd_p2_xtgzzt->setObjectName(QString::fromUtf8("lcd_p2_xtgzzt"));
        lcd_p2_xtgzzt->setGeometry(QRect(240, 90, 51, 16));
        lcd_p2_xtgzzt->setAutoFillBackground(false);
        lcd_p2_xtgzzt->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_p2_xtgzzt->setFrameShape(QFrame::NoFrame);
        lcd_p2_xtgzzt->setFrameShadow(QFrame::Raised);
        lcd_p2_xtgzzt->setSmallDecimalPoint(false);
        lcd_p2_xtgzzt->setMode(QLCDNumber::Dec);
        lcd_p2_xtgzzt->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_12 = new QLabel(frame);
        label_xtzy_12->setObjectName(QString::fromUtf8("label_xtzy_12"));
        label_xtzy_12->setGeometry(QRect(300, 10, 71, 17));
        label_xtzy_13 = new QLabel(frame);
        label_xtzy_13->setObjectName(QString::fromUtf8("label_xtzy_13"));
        label_xtzy_13->setGeometry(QRect(300, 50, 71, 17));
        lcd_p2_jyzz = new QLCDNumber(frame);
        lcd_p2_jyzz->setObjectName(QString::fromUtf8("lcd_p2_jyzz"));
        lcd_p2_jyzz->setGeometry(QRect(370, 30, 51, 16));
        lcd_p2_jyzz->setAutoFillBackground(false);
        lcd_p2_jyzz->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_p2_jyzz->setFrameShape(QFrame::NoFrame);
        lcd_p2_jyzz->setFrameShadow(QFrame::Raised);
        lcd_p2_jyzz->setSmallDecimalPoint(false);
        lcd_p2_jyzz->setMode(QLCDNumber::Dec);
        lcd_p2_jyzz->setSegmentStyle(QLCDNumber::Flat);
        lcd_p2_dczt = new QLCDNumber(frame);
        lcd_p2_dczt->setObjectName(QString::fromUtf8("lcd_p2_dczt"));
        lcd_p2_dczt->setGeometry(QRect(370, 10, 51, 16));
        lcd_p2_dczt->setAutoFillBackground(false);
        lcd_p2_dczt->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_p2_dczt->setFrameShape(QFrame::NoFrame);
        lcd_p2_dczt->setFrameShadow(QFrame::Raised);
        lcd_p2_dczt->setSmallDecimalPoint(false);
        lcd_p2_dczt->setMode(QLCDNumber::Dec);
        lcd_p2_dczt->setSegmentStyle(QLCDNumber::Flat);
        lcd_p2_smzq = new QLCDNumber(frame);
        lcd_p2_smzq->setObjectName(QString::fromUtf8("lcd_p2_smzq"));
        lcd_p2_smzq->setGeometry(QRect(370, 50, 51, 16));
        lcd_p2_smzq->setAutoFillBackground(false);
        lcd_p2_smzq->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_p2_smzq->setFrameShape(QFrame::NoFrame);
        lcd_p2_smzq->setFrameShadow(QFrame::Raised);
        lcd_p2_smzq->setSmallDecimalPoint(false);
        lcd_p2_smzq->setMode(QLCDNumber::Dec);
        lcd_p2_smzq->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_15 = new QLabel(frame);
        label_xtzy_15->setObjectName(QString::fromUtf8("label_xtzy_15"));
        label_xtzy_15->setGeometry(QRect(300, 30, 71, 17));
        label_cluster = new QLabel(tab_cjbxx);
        label_cluster->setObjectName(QString::fromUtf8("label_cluster"));
        label_cluster->setGeometry(QRect(60, 20, 71, 81));
        label_cluster->setFrameShape(QFrame::StyledPanel);
        label_cluster->setFrameShadow(QFrame::Raised);
        label_cluster->setAlignment(Qt::AlignCenter);
        frame_2 = new QFrame(tab_cjbxx);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(20, 140, 161, 231));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        label_zgdy = new QLabel(frame_2);
        label_zgdy->setObjectName(QString::fromUtf8("label_zgdy"));
        label_zgdy->setGeometry(QRect(20, 30, 62, 17));
        lcd_p2_zgdy = new QLCDNumber(frame_2);
        lcd_p2_zgdy->setObjectName(QString::fromUtf8("lcd_p2_zgdy"));
        lcd_p2_zgdy->setGeometry(QRect(80, 20, 71, 31));
        lcd_p2_zgdy->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_p2_zgdy->setSegmentStyle(QLCDNumber::Flat);
        lcd_p2_zddy = new QLCDNumber(frame_2);
        lcd_p2_zddy->setObjectName(QString::fromUtf8("lcd_p2_zddy"));
        lcd_p2_zddy->setGeometry(QRect(80, 60, 71, 31));
        lcd_p2_zddy->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_p2_zddy->setSegmentStyle(QLCDNumber::Flat);
        label_zddy = new QLabel(frame_2);
        label_zddy->setObjectName(QString::fromUtf8("label_zddy"));
        label_zddy->setGeometry(QRect(20, 70, 62, 17));
        lcd_p2_zgwd = new QLCDNumber(frame_2);
        lcd_p2_zgwd->setObjectName(QString::fromUtf8("lcd_p2_zgwd"));
        lcd_p2_zgwd->setGeometry(QRect(80, 100, 71, 31));
        lcd_p2_zgwd->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_p2_zgwd->setSegmentStyle(QLCDNumber::Flat);
        label_zgwd = new QLabel(frame_2);
        label_zgwd->setObjectName(QString::fromUtf8("label_zgwd"));
        label_zgwd->setGeometry(QRect(20, 110, 62, 17));
        lcd_p2_zdwd = new QLCDNumber(frame_2);
        lcd_p2_zdwd->setObjectName(QString::fromUtf8("lcd_p2_zdwd"));
        lcd_p2_zdwd->setGeometry(QRect(80, 140, 71, 31));
        lcd_p2_zdwd->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_p2_zdwd->setSegmentStyle(QLCDNumber::Flat);
        label_zdwd = new QLabel(frame_2);
        label_zdwd->setObjectName(QString::fromUtf8("label_zdwd"));
        label_zdwd->setGeometry(QRect(20, 150, 62, 17));
        lcd_p2_szwz = new QLCDNumber(frame_2);
        lcd_p2_szwz->setObjectName(QString::fromUtf8("lcd_p2_szwz"));
        lcd_p2_szwz->setGeometry(QRect(80, 180, 71, 31));
        lcd_p2_szwz->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_p2_szwz->setSegmentStyle(QLCDNumber::Flat);
        label_szwz = new QLabel(frame_2);
        label_szwz->setObjectName(QString::fromUtf8("label_szwz"));
        label_szwz->setGeometry(QRect(20, 190, 62, 17));
        frame_3 = new QFrame(tab_cjbxx);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(200, 140, 431, 231));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Raised);
        tableView = new QTableView(frame_3);
        tableView->setObjectName(QString::fromUtf8("tableView"));
        tableView->setGeometry(QRect(20, 10, 391, 201));
        tableView->setShowGrid(true);
        tableView->setGridStyle(Qt::SolidLine);
        tableView->setCornerButtonEnabled(true);
        tableView->horizontalHeader()->setVisible(false);
        tabWidget->addTab(tab_cjbxx, QString());
        tab_cxxxx = new QWidget();
        tab_cxxxx->setObjectName(QString::fromUtf8("tab_cxxxx"));
        label_cluster_2 = new QLabel(tab_cxxxx);
        label_cluster_2->setObjectName(QString::fromUtf8("label_cluster_2"));
        label_cluster_2->setGeometry(QRect(60, 20, 71, 81));
        label_cluster_2->setFrameShape(QFrame::StyledPanel);
        label_cluster_2->setFrameShadow(QFrame::Raised);
        label_cluster_2->setAlignment(Qt::AlignCenter);
        pbutton_left_2 = new QPushButton(tab_cxxxx);
        pbutton_left_2->setObjectName(QString::fromUtf8("pbutton_left_2"));
        pbutton_left_2->setGeometry(QRect(20, 20, 31, 81));
        pbutton_right_2 = new QPushButton(tab_cxxxx);
        pbutton_right_2->setObjectName(QString::fromUtf8("pbutton_right_2"));
        pbutton_right_2->setGeometry(QRect(140, 20, 31, 81));
        comboBox = new QComboBox(tab_cxxxx);
        comboBox->setObjectName(QString::fromUtf8("comboBox"));
        comboBox->setGeometry(QRect(40, 110, 111, 27));
        frame_4 = new QFrame(tab_cxxxx);
        frame_4->setObjectName(QString::fromUtf8("frame_4"));
        frame_4->setGeometry(QRect(20, 150, 611, 261));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Raised);
        frame_5 = new QFrame(tab_cxxxx);
        frame_5->setObjectName(QString::fromUtf8("frame_5"));
        frame_5->setGeometry(QRect(190, 20, 441, 111));
        frame_5->setFrameShape(QFrame::StyledPanel);
        frame_5->setFrameShadow(QFrame::Raised);
        lcdNumber_7 = new QLCDNumber(frame_5);
        lcdNumber_7->setObjectName(QString::fromUtf8("lcdNumber_7"));
        lcdNumber_7->setGeometry(QRect(70, 50, 71, 31));
        lcdNumber_7->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcdNumber_7->setSegmentStyle(QLCDNumber::Flat);
        label_7 = new QLabel(frame_5);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(10, 60, 62, 17));
        lcdNumber_8 = new QLCDNumber(frame_5);
        lcdNumber_8->setObjectName(QString::fromUtf8("lcdNumber_8"));
        lcdNumber_8->setGeometry(QRect(210, 10, 71, 31));
        lcdNumber_8->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcdNumber_8->setSegmentStyle(QLCDNumber::Flat);
        label_8 = new QLabel(frame_5);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(150, 20, 62, 17));
        lcdNumber_9 = new QLCDNumber(frame_5);
        lcdNumber_9->setObjectName(QString::fromUtf8("lcdNumber_9"));
        lcdNumber_9->setGeometry(QRect(210, 50, 71, 31));
        lcdNumber_9->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcdNumber_9->setSegmentStyle(QLCDNumber::Flat);
        label_9 = new QLabel(frame_5);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(150, 60, 62, 17));
        lcdNumber_10 = new QLCDNumber(frame_5);
        lcdNumber_10->setObjectName(QString::fromUtf8("lcdNumber_10"));
        lcdNumber_10->setGeometry(QRect(350, 10, 71, 31));
        lcdNumber_10->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcdNumber_10->setSegmentStyle(QLCDNumber::Flat);
        label_10 = new QLabel(frame_5);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(290, 20, 62, 17));
        lcdNumber_11 = new QLCDNumber(frame_5);
        lcdNumber_11->setObjectName(QString::fromUtf8("lcdNumber_11"));
        lcdNumber_11->setGeometry(QRect(350, 50, 71, 31));
        lcdNumber_11->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcdNumber_11->setSegmentStyle(QLCDNumber::Flat);
        label_11 = new QLabel(frame_5);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(290, 60, 62, 17));
        lcdNumber_6 = new QLCDNumber(tab_cxxxx);
        lcdNumber_6->setObjectName(QString::fromUtf8("lcdNumber_6"));
        lcdNumber_6->setGeometry(QRect(260, 30, 71, 31));
        lcdNumber_6->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcdNumber_6->setSegmentStyle(QLCDNumber::Flat);
        label_6 = new QLabel(tab_cxxxx);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(200, 40, 62, 17));
        lcd_zdy_12 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_12->setObjectName(QString::fromUtf8("lcd_zdy_12"));
        lcd_zdy_12->setGeometry(QRect(110, 170, 51, 16));
        lcd_zdy_12->setAutoFillBackground(false);
        lcd_zdy_12->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_12->setFrameShape(QFrame::NoFrame);
        lcd_zdy_12->setFrameShadow(QFrame::Raised);
        lcd_zdy_12->setSmallDecimalPoint(false);
        lcd_zdy_12->setMode(QLCDNumber::Dec);
        lcd_zdy_12->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_11 = new QLabel(tab_cxxxx);
        label_xtzy_11->setObjectName(QString::fromUtf8("label_xtzy_11"));
        label_xtzy_11->setGeometry(QRect(50, 170, 62, 17));
        lcd_zdy_16 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_16->setObjectName(QString::fromUtf8("lcd_zdy_16"));
        lcd_zdy_16->setGeometry(QRect(110, 200, 51, 16));
        lcd_zdy_16->setAutoFillBackground(false);
        lcd_zdy_16->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_16->setFrameShape(QFrame::NoFrame);
        lcd_zdy_16->setFrameShadow(QFrame::Raised);
        lcd_zdy_16->setSmallDecimalPoint(false);
        lcd_zdy_16->setMode(QLCDNumber::Dec);
        lcd_zdy_16->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_14 = new QLabel(tab_cxxxx);
        label_xtzy_14->setObjectName(QString::fromUtf8("label_xtzy_14"));
        label_xtzy_14->setGeometry(QRect(50, 200, 62, 17));
        lcd_zdy_17 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_17->setObjectName(QString::fromUtf8("lcd_zdy_17"));
        lcd_zdy_17->setGeometry(QRect(110, 230, 51, 16));
        lcd_zdy_17->setAutoFillBackground(false);
        lcd_zdy_17->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_17->setFrameShape(QFrame::NoFrame);
        lcd_zdy_17->setFrameShadow(QFrame::Raised);
        lcd_zdy_17->setSmallDecimalPoint(false);
        lcd_zdy_17->setMode(QLCDNumber::Dec);
        lcd_zdy_17->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_16 = new QLabel(tab_cxxxx);
        label_xtzy_16->setObjectName(QString::fromUtf8("label_xtzy_16"));
        label_xtzy_16->setGeometry(QRect(50, 230, 62, 17));
        lcd_zdy_18 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_18->setObjectName(QString::fromUtf8("lcd_zdy_18"));
        lcd_zdy_18->setGeometry(QRect(110, 260, 51, 16));
        lcd_zdy_18->setAutoFillBackground(false);
        lcd_zdy_18->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_18->setFrameShape(QFrame::NoFrame);
        lcd_zdy_18->setFrameShadow(QFrame::Raised);
        lcd_zdy_18->setSmallDecimalPoint(false);
        lcd_zdy_18->setMode(QLCDNumber::Dec);
        lcd_zdy_18->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_17 = new QLabel(tab_cxxxx);
        label_xtzy_17->setObjectName(QString::fromUtf8("label_xtzy_17"));
        label_xtzy_17->setGeometry(QRect(50, 260, 62, 17));
        lcd_zdy_19 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_19->setObjectName(QString::fromUtf8("lcd_zdy_19"));
        lcd_zdy_19->setGeometry(QRect(110, 290, 51, 16));
        lcd_zdy_19->setAutoFillBackground(false);
        lcd_zdy_19->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_19->setFrameShape(QFrame::NoFrame);
        lcd_zdy_19->setFrameShadow(QFrame::Raised);
        lcd_zdy_19->setSmallDecimalPoint(false);
        lcd_zdy_19->setMode(QLCDNumber::Dec);
        lcd_zdy_19->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_18 = new QLabel(tab_cxxxx);
        label_xtzy_18->setObjectName(QString::fromUtf8("label_xtzy_18"));
        label_xtzy_18->setGeometry(QRect(50, 290, 62, 17));
        label_xtzy_19 = new QLabel(tab_cxxxx);
        label_xtzy_19->setObjectName(QString::fromUtf8("label_xtzy_19"));
        label_xtzy_19->setGeometry(QRect(180, 230, 62, 17));
        label_xtzy_20 = new QLabel(tab_cxxxx);
        label_xtzy_20->setObjectName(QString::fromUtf8("label_xtzy_20"));
        label_xtzy_20->setGeometry(QRect(180, 170, 62, 17));
        label_xtzy_21 = new QLabel(tab_cxxxx);
        label_xtzy_21->setObjectName(QString::fromUtf8("label_xtzy_21"));
        label_xtzy_21->setGeometry(QRect(180, 290, 62, 17));
        label_xtzy_22 = new QLabel(tab_cxxxx);
        label_xtzy_22->setObjectName(QString::fromUtf8("label_xtzy_22"));
        label_xtzy_22->setGeometry(QRect(180, 260, 62, 17));
        lcd_zdy_20 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_20->setObjectName(QString::fromUtf8("lcd_zdy_20"));
        lcd_zdy_20->setGeometry(QRect(240, 290, 51, 16));
        lcd_zdy_20->setAutoFillBackground(false);
        lcd_zdy_20->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_20->setFrameShape(QFrame::NoFrame);
        lcd_zdy_20->setFrameShadow(QFrame::Raised);
        lcd_zdy_20->setSmallDecimalPoint(false);
        lcd_zdy_20->setMode(QLCDNumber::Dec);
        lcd_zdy_20->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_23 = new QLabel(tab_cxxxx);
        label_xtzy_23->setObjectName(QString::fromUtf8("label_xtzy_23"));
        label_xtzy_23->setGeometry(QRect(180, 200, 62, 17));
        lcd_zdy_21 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_21->setObjectName(QString::fromUtf8("lcd_zdy_21"));
        lcd_zdy_21->setGeometry(QRect(240, 200, 51, 16));
        lcd_zdy_21->setAutoFillBackground(false);
        lcd_zdy_21->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_21->setFrameShape(QFrame::NoFrame);
        lcd_zdy_21->setFrameShadow(QFrame::Raised);
        lcd_zdy_21->setSmallDecimalPoint(false);
        lcd_zdy_21->setMode(QLCDNumber::Dec);
        lcd_zdy_21->setSegmentStyle(QLCDNumber::Flat);
        lcd_zdy_22 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_22->setObjectName(QString::fromUtf8("lcd_zdy_22"));
        lcd_zdy_22->setGeometry(QRect(240, 260, 51, 16));
        lcd_zdy_22->setAutoFillBackground(false);
        lcd_zdy_22->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_22->setFrameShape(QFrame::NoFrame);
        lcd_zdy_22->setFrameShadow(QFrame::Raised);
        lcd_zdy_22->setSmallDecimalPoint(false);
        lcd_zdy_22->setMode(QLCDNumber::Dec);
        lcd_zdy_22->setSegmentStyle(QLCDNumber::Flat);
        lcd_zdy_23 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_23->setObjectName(QString::fromUtf8("lcd_zdy_23"));
        lcd_zdy_23->setGeometry(QRect(240, 170, 51, 16));
        lcd_zdy_23->setAutoFillBackground(false);
        lcd_zdy_23->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_23->setFrameShape(QFrame::NoFrame);
        lcd_zdy_23->setFrameShadow(QFrame::Raised);
        lcd_zdy_23->setSmallDecimalPoint(false);
        lcd_zdy_23->setMode(QLCDNumber::Dec);
        lcd_zdy_23->setSegmentStyle(QLCDNumber::Flat);
        lcd_zdy_24 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_24->setObjectName(QString::fromUtf8("lcd_zdy_24"));
        lcd_zdy_24->setGeometry(QRect(240, 230, 51, 16));
        lcd_zdy_24->setAutoFillBackground(false);
        lcd_zdy_24->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_24->setFrameShape(QFrame::NoFrame);
        lcd_zdy_24->setFrameShadow(QFrame::Raised);
        lcd_zdy_24->setSmallDecimalPoint(false);
        lcd_zdy_24->setMode(QLCDNumber::Dec);
        lcd_zdy_24->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_24 = new QLabel(tab_cxxxx);
        label_xtzy_24->setObjectName(QString::fromUtf8("label_xtzy_24"));
        label_xtzy_24->setGeometry(QRect(310, 230, 62, 17));
        label_xtzy_25 = new QLabel(tab_cxxxx);
        label_xtzy_25->setObjectName(QString::fromUtf8("label_xtzy_25"));
        label_xtzy_25->setGeometry(QRect(310, 170, 62, 17));
        label_xtzy_26 = new QLabel(tab_cxxxx);
        label_xtzy_26->setObjectName(QString::fromUtf8("label_xtzy_26"));
        label_xtzy_26->setGeometry(QRect(310, 290, 62, 17));
        label_xtzy_27 = new QLabel(tab_cxxxx);
        label_xtzy_27->setObjectName(QString::fromUtf8("label_xtzy_27"));
        label_xtzy_27->setGeometry(QRect(310, 260, 62, 17));
        lcd_zdy_25 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_25->setObjectName(QString::fromUtf8("lcd_zdy_25"));
        lcd_zdy_25->setGeometry(QRect(370, 290, 51, 16));
        lcd_zdy_25->setAutoFillBackground(false);
        lcd_zdy_25->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_25->setFrameShape(QFrame::NoFrame);
        lcd_zdy_25->setFrameShadow(QFrame::Raised);
        lcd_zdy_25->setSmallDecimalPoint(false);
        lcd_zdy_25->setMode(QLCDNumber::Dec);
        lcd_zdy_25->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_28 = new QLabel(tab_cxxxx);
        label_xtzy_28->setObjectName(QString::fromUtf8("label_xtzy_28"));
        label_xtzy_28->setGeometry(QRect(310, 200, 62, 17));
        lcd_zdy_26 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_26->setObjectName(QString::fromUtf8("lcd_zdy_26"));
        lcd_zdy_26->setGeometry(QRect(370, 200, 51, 16));
        lcd_zdy_26->setAutoFillBackground(false);
        lcd_zdy_26->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_26->setFrameShape(QFrame::NoFrame);
        lcd_zdy_26->setFrameShadow(QFrame::Raised);
        lcd_zdy_26->setSmallDecimalPoint(false);
        lcd_zdy_26->setMode(QLCDNumber::Dec);
        lcd_zdy_26->setSegmentStyle(QLCDNumber::Flat);
        lcd_zdy_27 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_27->setObjectName(QString::fromUtf8("lcd_zdy_27"));
        lcd_zdy_27->setGeometry(QRect(370, 260, 51, 16));
        lcd_zdy_27->setAutoFillBackground(false);
        lcd_zdy_27->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_27->setFrameShape(QFrame::NoFrame);
        lcd_zdy_27->setFrameShadow(QFrame::Raised);
        lcd_zdy_27->setSmallDecimalPoint(false);
        lcd_zdy_27->setMode(QLCDNumber::Dec);
        lcd_zdy_27->setSegmentStyle(QLCDNumber::Flat);
        lcd_zdy_28 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_28->setObjectName(QString::fromUtf8("lcd_zdy_28"));
        lcd_zdy_28->setGeometry(QRect(370, 170, 51, 16));
        lcd_zdy_28->setAutoFillBackground(false);
        lcd_zdy_28->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_28->setFrameShape(QFrame::NoFrame);
        lcd_zdy_28->setFrameShadow(QFrame::Raised);
        lcd_zdy_28->setSmallDecimalPoint(false);
        lcd_zdy_28->setMode(QLCDNumber::Dec);
        lcd_zdy_28->setSegmentStyle(QLCDNumber::Flat);
        lcd_zdy_29 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_29->setObjectName(QString::fromUtf8("lcd_zdy_29"));
        lcd_zdy_29->setGeometry(QRect(370, 230, 51, 16));
        lcd_zdy_29->setAutoFillBackground(false);
        lcd_zdy_29->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_29->setFrameShape(QFrame::NoFrame);
        lcd_zdy_29->setFrameShadow(QFrame::Raised);
        lcd_zdy_29->setSmallDecimalPoint(false);
        lcd_zdy_29->setMode(QLCDNumber::Dec);
        lcd_zdy_29->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_29 = new QLabel(tab_cxxxx);
        label_xtzy_29->setObjectName(QString::fromUtf8("label_xtzy_29"));
        label_xtzy_29->setGeometry(QRect(440, 230, 62, 17));
        label_xtzy_30 = new QLabel(tab_cxxxx);
        label_xtzy_30->setObjectName(QString::fromUtf8("label_xtzy_30"));
        label_xtzy_30->setGeometry(QRect(440, 170, 62, 17));
        label_xtzy_31 = new QLabel(tab_cxxxx);
        label_xtzy_31->setObjectName(QString::fromUtf8("label_xtzy_31"));
        label_xtzy_31->setGeometry(QRect(440, 290, 62, 17));
        label_xtzy_32 = new QLabel(tab_cxxxx);
        label_xtzy_32->setObjectName(QString::fromUtf8("label_xtzy_32"));
        label_xtzy_32->setGeometry(QRect(440, 260, 62, 17));
        lcd_zdy_30 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_30->setObjectName(QString::fromUtf8("lcd_zdy_30"));
        lcd_zdy_30->setGeometry(QRect(500, 290, 51, 16));
        lcd_zdy_30->setAutoFillBackground(false);
        lcd_zdy_30->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_30->setFrameShape(QFrame::NoFrame);
        lcd_zdy_30->setFrameShadow(QFrame::Raised);
        lcd_zdy_30->setSmallDecimalPoint(false);
        lcd_zdy_30->setMode(QLCDNumber::Dec);
        lcd_zdy_30->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_33 = new QLabel(tab_cxxxx);
        label_xtzy_33->setObjectName(QString::fromUtf8("label_xtzy_33"));
        label_xtzy_33->setGeometry(QRect(440, 200, 62, 17));
        lcd_zdy_31 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_31->setObjectName(QString::fromUtf8("lcd_zdy_31"));
        lcd_zdy_31->setGeometry(QRect(500, 200, 51, 16));
        lcd_zdy_31->setAutoFillBackground(false);
        lcd_zdy_31->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_31->setFrameShape(QFrame::NoFrame);
        lcd_zdy_31->setFrameShadow(QFrame::Raised);
        lcd_zdy_31->setSmallDecimalPoint(false);
        lcd_zdy_31->setMode(QLCDNumber::Dec);
        lcd_zdy_31->setSegmentStyle(QLCDNumber::Flat);
        lcd_zdy_32 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_32->setObjectName(QString::fromUtf8("lcd_zdy_32"));
        lcd_zdy_32->setGeometry(QRect(500, 260, 51, 16));
        lcd_zdy_32->setAutoFillBackground(false);
        lcd_zdy_32->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_32->setFrameShape(QFrame::NoFrame);
        lcd_zdy_32->setFrameShadow(QFrame::Raised);
        lcd_zdy_32->setSmallDecimalPoint(false);
        lcd_zdy_32->setMode(QLCDNumber::Dec);
        lcd_zdy_32->setSegmentStyle(QLCDNumber::Flat);
        lcd_zdy_33 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_33->setObjectName(QString::fromUtf8("lcd_zdy_33"));
        lcd_zdy_33->setGeometry(QRect(500, 170, 51, 16));
        lcd_zdy_33->setAutoFillBackground(false);
        lcd_zdy_33->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_33->setFrameShape(QFrame::NoFrame);
        lcd_zdy_33->setFrameShadow(QFrame::Raised);
        lcd_zdy_33->setSmallDecimalPoint(false);
        lcd_zdy_33->setMode(QLCDNumber::Dec);
        lcd_zdy_33->setSegmentStyle(QLCDNumber::Flat);
        lcd_zdy_34 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_34->setObjectName(QString::fromUtf8("lcd_zdy_34"));
        lcd_zdy_34->setGeometry(QRect(500, 230, 51, 16));
        lcd_zdy_34->setAutoFillBackground(false);
        lcd_zdy_34->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_34->setFrameShape(QFrame::NoFrame);
        lcd_zdy_34->setFrameShadow(QFrame::Raised);
        lcd_zdy_34->setSmallDecimalPoint(false);
        lcd_zdy_34->setMode(QLCDNumber::Dec);
        lcd_zdy_34->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_34 = new QLabel(tab_cxxxx);
        label_xtzy_34->setObjectName(QString::fromUtf8("label_xtzy_34"));
        label_xtzy_34->setGeometry(QRect(310, 320, 62, 17));
        lcd_zdy_35 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_35->setObjectName(QString::fromUtf8("lcd_zdy_35"));
        lcd_zdy_35->setGeometry(QRect(370, 320, 51, 16));
        lcd_zdy_35->setAutoFillBackground(false);
        lcd_zdy_35->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_35->setFrameShape(QFrame::NoFrame);
        lcd_zdy_35->setFrameShadow(QFrame::Raised);
        lcd_zdy_35->setSmallDecimalPoint(false);
        lcd_zdy_35->setMode(QLCDNumber::Dec);
        lcd_zdy_35->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_35 = new QLabel(tab_cxxxx);
        label_xtzy_35->setObjectName(QString::fromUtf8("label_xtzy_35"));
        label_xtzy_35->setGeometry(QRect(440, 320, 62, 17));
        label_xtzy_36 = new QLabel(tab_cxxxx);
        label_xtzy_36->setObjectName(QString::fromUtf8("label_xtzy_36"));
        label_xtzy_36->setGeometry(QRect(50, 320, 62, 17));
        lcd_zdy_36 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_36->setObjectName(QString::fromUtf8("lcd_zdy_36"));
        lcd_zdy_36->setGeometry(QRect(240, 320, 51, 16));
        lcd_zdy_36->setAutoFillBackground(false);
        lcd_zdy_36->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_36->setFrameShape(QFrame::NoFrame);
        lcd_zdy_36->setFrameShadow(QFrame::Raised);
        lcd_zdy_36->setSmallDecimalPoint(false);
        lcd_zdy_36->setMode(QLCDNumber::Dec);
        lcd_zdy_36->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_37 = new QLabel(tab_cxxxx);
        label_xtzy_37->setObjectName(QString::fromUtf8("label_xtzy_37"));
        label_xtzy_37->setGeometry(QRect(180, 320, 62, 17));
        lcd_zdy_37 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_37->setObjectName(QString::fromUtf8("lcd_zdy_37"));
        lcd_zdy_37->setGeometry(QRect(110, 320, 51, 16));
        lcd_zdy_37->setAutoFillBackground(false);
        lcd_zdy_37->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_37->setFrameShape(QFrame::NoFrame);
        lcd_zdy_37->setFrameShadow(QFrame::Raised);
        lcd_zdy_37->setSmallDecimalPoint(false);
        lcd_zdy_37->setMode(QLCDNumber::Dec);
        lcd_zdy_37->setSegmentStyle(QLCDNumber::Flat);
        lcd_zdy_38 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_38->setObjectName(QString::fromUtf8("lcd_zdy_38"));
        lcd_zdy_38->setGeometry(QRect(500, 320, 51, 16));
        lcd_zdy_38->setAutoFillBackground(false);
        lcd_zdy_38->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_38->setFrameShape(QFrame::NoFrame);
        lcd_zdy_38->setFrameShadow(QFrame::Raised);
        lcd_zdy_38->setSmallDecimalPoint(false);
        lcd_zdy_38->setMode(QLCDNumber::Dec);
        lcd_zdy_38->setSegmentStyle(QLCDNumber::Flat);
        lcd_zdy_39 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_39->setObjectName(QString::fromUtf8("lcd_zdy_39"));
        lcd_zdy_39->setGeometry(QRect(370, 350, 51, 16));
        lcd_zdy_39->setAutoFillBackground(false);
        lcd_zdy_39->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_39->setFrameShape(QFrame::NoFrame);
        lcd_zdy_39->setFrameShadow(QFrame::Raised);
        lcd_zdy_39->setSmallDecimalPoint(false);
        lcd_zdy_39->setMode(QLCDNumber::Dec);
        lcd_zdy_39->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_38 = new QLabel(tab_cxxxx);
        label_xtzy_38->setObjectName(QString::fromUtf8("label_xtzy_38"));
        label_xtzy_38->setGeometry(QRect(180, 350, 62, 17));
        label_xtzy_39 = new QLabel(tab_cxxxx);
        label_xtzy_39->setObjectName(QString::fromUtf8("label_xtzy_39"));
        label_xtzy_39->setGeometry(QRect(50, 350, 62, 17));
        lcd_zdy_40 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_40->setObjectName(QString::fromUtf8("lcd_zdy_40"));
        lcd_zdy_40->setGeometry(QRect(110, 350, 51, 16));
        lcd_zdy_40->setAutoFillBackground(false);
        lcd_zdy_40->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_40->setFrameShape(QFrame::NoFrame);
        lcd_zdy_40->setFrameShadow(QFrame::Raised);
        lcd_zdy_40->setSmallDecimalPoint(false);
        lcd_zdy_40->setMode(QLCDNumber::Dec);
        lcd_zdy_40->setSegmentStyle(QLCDNumber::Flat);
        lcd_zdy_41 = new QLCDNumber(tab_cxxxx);
        lcd_zdy_41->setObjectName(QString::fromUtf8("lcd_zdy_41"));
        lcd_zdy_41->setGeometry(QRect(240, 350, 51, 16));
        lcd_zdy_41->setAutoFillBackground(false);
        lcd_zdy_41->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lcd_zdy_41->setFrameShape(QFrame::NoFrame);
        lcd_zdy_41->setFrameShadow(QFrame::Raised);
        lcd_zdy_41->setSmallDecimalPoint(false);
        lcd_zdy_41->setMode(QLCDNumber::Dec);
        lcd_zdy_41->setSegmentStyle(QLCDNumber::Flat);
        label_xtzy_40 = new QLabel(tab_cxxxx);
        label_xtzy_40->setObjectName(QString::fromUtf8("label_xtzy_40"));
        label_xtzy_40->setGeometry(QRect(310, 350, 62, 17));
        tabWidget->addTab(tab_cxxxx, QString());
        tab_gzxx = new QWidget();
        tab_gzxx->setObjectName(QString::fromUtf8("tab_gzxx"));
        tableView_2 = new QTableView(tab_gzxx);
        tableView_2->setObjectName(QString::fromUtf8("tableView_2"));
        tableView_2->setGeometry(QRect(30, 30, 591, 371));
        tabWidget->addTab(tab_gzxx, QString());
        tab_xtrz = new QWidget();
        tab_xtrz->setObjectName(QString::fromUtf8("tab_xtrz"));
        text_log = new QTextBrowser(tab_xtrz);
        text_log->setObjectName(QString::fromUtf8("text_log"));
        text_log->setGeometry(QRect(20, 20, 611, 401));
        tabWidget->addTab(tab_xtrz, QString());

        gridLayout->addWidget(tabWidget, 0, 0, 1, 1);

        QWidget::setTabOrder(tabWidget, text_zdy);

        retranslateUi(Widget);

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(Widget);
    } // setupUi

    void retranslateUi(QWidget *Widget)
    {
        Widget->setWindowTitle(QApplication::translate("Widget", "\347\233\221\346\216\247\347\273\210\347\253\257", 0, QApplication::UnicodeUTF8));
        text_zdy->setHtml(QApplication::translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'10pt';\">\346\200\273\347\224\265\345\216\213\357\274\210V\357\274\211</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        text_zdl->setHtml(QApplication::translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\346\200\273\347\224\265\346\265\201\357\274\210A\357\274\211</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_header->setText(QApplication::translate("Widget", "\351\225\207\346\261\237\347\247\221\344\277\241\345\212\250\345\212\233\347\263\273\347\273\237\350\256\276\350\256\241\347\240\224\347\251\266\346\234\211\351\231\220\345\205\254\345\217\270", 0, QApplication::UnicodeUTF8));
        text_soc->setHtml(QApplication::translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">SOC(%)</p></body></html>", 0, QApplication::UnicodeUTF8));
        text_zdyc->setHtml(QApplication::translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\346\234\200\345\244\247\345\216\213\345\267\256\357\274\210V\357\274\211</p></body></html>", 0, QApplication::UnicodeUTF8));
        text_zdwc->setHtml(QApplication::translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\346\234\200\345\244\247\346\270\251\345\267\256\357\274\210V\357\274\211</p></body></html>", 0, QApplication::UnicodeUTF8));
        text_zddy->setHtml(QApplication::translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\346\234\200\345\244\247\347\224\265\345\216\213</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_zddy_loc->setText(QApplication::translate("Widget", "Loc:", 0, QApplication::UnicodeUTF8));
        label_zxdy_loc->setText(QApplication::translate("Widget", "Loc:", 0, QApplication::UnicodeUTF8));
        text_zxdy->setHtml(QApplication::translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\346\234\200\345\260\217\347\224\265\345\216\213</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_zgwd_loc->setText(QApplication::translate("Widget", "Loc:", 0, QApplication::UnicodeUTF8));
        text_zdwd->setHtml(QApplication::translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\346\234\200\344\275\216\346\270\251\345\272\246</p></body></html>", 0, QApplication::UnicodeUTF8));
        text_zgwd->setHtml(QApplication::translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\346\234\200\351\253\230\346\270\251\345\272\246</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_zdwd_loc->setText(QApplication::translate("Widget", "Loc:", 0, QApplication::UnicodeUTF8));
        label_pjdy_loc->setText(QApplication::translate("Widget", "Loc:", 0, QApplication::UnicodeUTF8));
        text_xtzt->setHtml(QApplication::translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\347\263\273\347\273\237\347\212\266\346\200\201</p></body></html>", 0, QApplication::UnicodeUTF8));
        text_pjdy->setHtml(QApplication::translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\345\271\263\345\235\207\347\224\265\345\216\213</p></body></html>", 0, QApplication::UnicodeUTF8));
        text_c1->setHtml(QApplication::translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1</p></body></html>", 0, QApplication::UnicodeUTF8));
        text_c2->setHtml(QApplication::translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2</p></body></html>", 0, QApplication::UnicodeUTF8));
        text_c3->setHtml(QApplication::translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3</p></body></html>", 0, QApplication::UnicodeUTF8));
        text_c4->setHtml(QApplication::translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4</p></body></html>", 0, QApplication::UnicodeUTF8));
        text_c5->setHtml(QApplication::translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5</p></body></html>", 0, QApplication::UnicodeUTF8));
        text_c6->setHtml(QApplication::translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">6</p></body></html>", 0, QApplication::UnicodeUTF8));
        text_c7->setHtml(QApplication::translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">7</p></body></html>", 0, QApplication::UnicodeUTF8));
        text_c8->setHtml(QApplication::translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">8</p></body></html>", 0, QApplication::UnicodeUTF8));
        text_c9->setHtml(QApplication::translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">9</p></body></html>", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_xtxx), QApplication::translate("Widget", "\347\263\273\347\273\237\344\277\241\346\201\257", 0, QApplication::UnicodeUTF8));
        pbutton_right->setText(QApplication::translate("Widget", ">", 0, QApplication::UnicodeUTF8));
        pbutton_left->setText(QApplication::translate("Widget", "<", 0, QApplication::UnicodeUTF8));
        label_xtzy->setText(QApplication::translate("Widget", "\347\263\273\347\273\237\346\200\273\345\216\213", 0, QApplication::UnicodeUTF8));
        label_xtzy_2->setText(QApplication::translate("Widget", "\347\224\265\346\265\201", 0, QApplication::UnicodeUTF8));
        label_xtzy_3->setText(QApplication::translate("Widget", "SOC", 0, QApplication::UnicodeUTF8));
        label_xtzy_4->setText(QApplication::translate("Widget", "SOH", 0, QApplication::UnicodeUTF8));
        label_xtzy_5->setText(QApplication::translate("Widget", "\350\275\257\344\273\266\347\211\210\346\234\254\345\217\267", 0, QApplication::UnicodeUTF8));
        label_xtzy_6->setText(QApplication::translate("Widget", "\347\263\273\347\273\237\347\212\266\346\200\201", 0, QApplication::UnicodeUTF8));
        label_xtzy_7->setText(QApplication::translate("Widget", "\345\212\237\347\216\207", 0, QApplication::UnicodeUTF8));
        label_xtzy_8->setText(QApplication::translate("Widget", "\345\255\220\346\250\241\346\225\260\351\207\217", 0, QApplication::UnicodeUTF8));
        label_xtzy_9->setText(QApplication::translate("Widget", "\345\205\205\347\224\265\346\254\241\346\225\260", 0, QApplication::UnicodeUTF8));
        label_xtzy_10->setText(QApplication::translate("Widget", "\347\263\273\347\273\237\346\225\205\351\232\234\347\212\266\346\200\201", 0, QApplication::UnicodeUTF8));
        label_xtzy_12->setText(QApplication::translate("Widget", "\347\224\265\346\261\240\347\212\266\346\200\201", 0, QApplication::UnicodeUTF8));
        label_xtzy_13->setText(QApplication::translate("Widget", "\347\224\237\345\221\275\345\221\250\346\234\237", 0, QApplication::UnicodeUTF8));
        label_xtzy_15->setText(QApplication::translate("Widget", "\347\273\235\347\274\230\351\230\273\345\200\274", 0, QApplication::UnicodeUTF8));
        label_cluster->setText(QApplication::translate("Widget", "1", 0, QApplication::UnicodeUTF8));
        label_zgdy->setText(QApplication::translate("Widget", "\346\234\200\351\253\230\347\224\265\345\216\213", 0, QApplication::UnicodeUTF8));
        label_zddy->setText(QApplication::translate("Widget", "\346\234\200\344\275\216\347\224\265\345\216\213", 0, QApplication::UnicodeUTF8));
        label_zgwd->setText(QApplication::translate("Widget", "\346\234\200\351\253\230\346\270\251\345\272\246", 0, QApplication::UnicodeUTF8));
        label_zdwd->setText(QApplication::translate("Widget", "\346\234\200\344\275\216\346\270\251\345\272\246", 0, QApplication::UnicodeUTF8));
        label_szwz->setText(QApplication::translate("Widget", "\346\211\200\345\234\250\344\275\215\347\275\256", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_cjbxx), QApplication::translate("Widget", "\347\260\207\345\237\272\346\234\254\344\277\241\346\201\257", 0, QApplication::UnicodeUTF8));
        label_cluster_2->setText(QApplication::translate("Widget", "1", 0, QApplication::UnicodeUTF8));
        pbutton_left_2->setText(QApplication::translate("Widget", "<", 0, QApplication::UnicodeUTF8));
        pbutton_right_2->setText(QApplication::translate("Widget", ">", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("Widget", "\345\215\225\344\275\223\344\270\262\346\225\260", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("Widget", "\346\234\200\351\253\230\346\270\251\345\272\246", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("Widget", "\346\234\200\344\275\216\346\270\251\345\272\246", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("Widget", "\346\270\251\345\272\246\344\270\252\346\225\260", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("Widget", "\346\211\200\345\234\250\344\275\215\347\275\256", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("Widget", "\346\250\241\345\235\227\346\200\273\345\216\213", 0, QApplication::UnicodeUTF8));
        label_xtzy_11->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_14->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_16->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_17->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_18->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_19->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_20->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_21->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_22->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_23->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_24->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_25->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_26->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_27->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_28->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_29->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_30->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_31->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_32->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_33->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_34->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_35->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_36->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_37->setText(QApplication::translate("Widget", "\346\200\273\345\216\2131", 0, QApplication::UnicodeUTF8));
        label_xtzy_38->setText(QApplication::translate("Widget", "\346\270\251\345\272\2461", 0, QApplication::UnicodeUTF8));
        label_xtzy_39->setText(QApplication::translate("Widget", "\346\270\251\345\272\2461", 0, QApplication::UnicodeUTF8));
        label_xtzy_40->setText(QApplication::translate("Widget", "\346\270\251\345\272\2461", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_cxxxx), QApplication::translate("Widget", "\347\260\207\350\257\246\347\273\206\344\277\241\346\201\257", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_gzxx), QApplication::translate("Widget", "\346\225\205\351\232\234\344\277\241\346\201\257", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_xtrz), QApplication::translate("Widget", "\347\263\273\347\273\237\346\227\245\345\277\227", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class Widget: public Ui_Widget {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_WIDGET_H
